language: go

services:
  - docker

sudo: false

install: true

go:
  - 1.11.x
  - 1.12.x

env:
  - TEST_SUITE=integration_tests
  - TEST_SUITE=unit_tests

script:
  - if [ "$TEST_SUITE" = "unit_tests" ]; then make all; fi
  - if [ "$TEST_SUITE" = "integration_tests" ]; then make testall; fi